In [1]:
import numpy as np

## Numpy arrays

In [2]:
myList = [20,30,40] #liste oluşturdum

In [3]:
np.array(myList) # np ile listemi dizi haline getirdim

array([20, 30, 40])

In [4]:
matrixList = [[20,30,40],[50,60,70],[80,90,100]]

In [5]:
np.array(matrixList)

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [6]:
# np ile matrix oluştururken referans olarak illa liste kullanmamıza gerek yok range() fonksiyonuda kullanabilirizi

myList2 = range(0,20,2)
np.array(myList2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## arange

In [7]:
np.arange(0,10) # range fonksiyonunun numpy'de kullanımı ama bu yöntem ile direkt dizi oluşturuyoruz liste değil

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## zeros

In [8]:
np.zeros(5)  # sıfır oluşturmaya yarayan bir methoddur

array([0., 0., 0., 0., 0.])

In [9]:
#matrix şeklinde yazalım
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## ones

In [10]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [12]:
np.linspace(0,20,5) # belirttiğimiz numaralar arasında eşit olarak aralık bırakılmış şekilde dizi tanımlar 0-20 arası 5 birim mesafe koyarak git

array([ 0.,  5., 10., 15., 20.])

In [13]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [14]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [18]:
np.random.randn(8)             # rastgele sayıların döneceği bir dizi tanımlama işlemidir

array([ 0.30287904,  0.13128006,  0.20646907, -0.22888908,  0.12311901,
       -0.16072144,  0.1905775 , -2.16170268])

In [20]:
np.random.randn(3,3)  # matrixli şekilde de yapabiliyoruz

array([[-0.53495906,  1.50841566, -0.11350725],
       [-0.74213582,  0.60388479, -1.34251437],
       [ 0.84068417, -1.50018803,  0.05548457]])

In [26]:
np.random.randint(1,10)        # tekli bir şekilde rastgele bir sayı dönderir

7

In [27]:
np.random.randint(1,10,5)  # 5 tane rastgele sayı çeviriyor

array([7, 7, 5, 9, 9], dtype=int32)

In [29]:
# bunları bir değişkene tayabiliriz
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
benimRandomDizim = np.random.randint(0,40,10)
benimRandomDizim

array([ 6,  9,  8, 19,  2, 38, 31,  4,  0, 29], dtype=int32)

## numpy dizi methodları